In [1]:
import torch
import random
from collections import deque
from torch.nn.functional import relu, prelu

In [2]:
#todo: collect all incoming edges for coalescence (search how they do it so it's consistent)
#todo: after implementing message pass algorithm, move it to forward pass (if possible... and if it doesn't overcomplicate modularly changing out attention structures...)
#todo: try graph step passing new node and computational dependency subtrees--> trim subtrees and extend undiscovered. intuition: like a net with a ball (at new node), 
# cut off at k-hop depth

# GraphSearch for single hop message passing
### new approach: graph class with nodes with child and parent links (for step and computational dependency subtree creation)
###               step() can be a random (for now uniform random) selection from children. 
#### todo: implement k-hop dependency subtree creation and think about computational efficiency... Don't want to have exponential search overhead with hops...

In [491]:
#idea: could it be possible to completely decouple the procedurality of the network and just assume it converges to something useful? 
#... Just randomly (as a function of local in/out degree) sample a layer from the network each time and just keep walking... 
#... Maybe this still allows for multi-granularity analysis, just less organized. This idea relies on some notion of convergence I think. 
#todo: inverse relations are added to the predicate set...
#todo: make training script
#todo: can enhance expressiveness by making transformation & aggregation steps 3 layer mlp's each. (in the case of the r-gcn these are the embedding layers)
# other option: can add mlp layers before and after the gnn, as pre-processing layers.
# skip connections can be used to reduce oversmoothing I.e. k-hop 3 gets preprocessed and passed past k-hop 2 as well as into it (duplication) and just gets summed together with k-hop2 outputs
# note that R-GCN uses normalized sum aggregation Also has edge dropout before batch norm
# R-GCN uses full batch adam (rmsprop+momentum) for 400 epochs
# R-GCN activation = relu, but relu-->relu-->softmax for entity classification makes sense ofcourse.
# Note mail: t.a.p.pelletreau-duris@student.vu.nl
# can kind of see embeddings as eigenvectors of the implications of the structure of the graph under random walk
# check spectral node representation... its equal to the svd
# graph laplacian  adj matrix (alternative repr for adj matrix)--> decomp
# inverse relations and equality relations 

import torch
from torch.nn.functional import prelu, relu
import torch.nn as nn
from collections import defaultdict, deque
import random
EMBEDDING_SIZE = 5
DIM_W = 5

# def message():

class R_GCN():
    def __init__(self, x_dim, y_dim):
        super().__init__()
        self.flatten = nn.linear(x_dim, y_dim)

    def forward(self, node, graph, agg_method=torch.sum): #maybe handle k_hops outside? have it be a single layer...
        messages = node.collect_from_neighbours()
        aggregated = agg_method(torch.stack(messages)) + node.embedding
        linear = prelu(aggregated)
        #dropout, batch norm, 
        return


class Node:
    def __init__(self, id_):
        self.id = id_
        self.embedding = torch.rand(EMBEDDING_SIZE, dtype=torch.float16, requires_grad=True)
        self.features = {}
        self.parents = {}
        self.children = {}
        self.out_edges = []

    
    

    # def coalesce_dependencies(self, graph, vectors=None, k_hop=2, method=torch.sum):
    #     #todo: fix... my brain is fried >,,<
    #     #idea: change to single node aggregation function and collect parents/loop in forward function of R-GCN.
    #     if vectors is None:
    #         vectors = []
    #     if k_hop <= 0:
    #         return self.embedding, vectors, k_hop
    #     incoming_messages_by_layer = {}
        
    #     for parent, labels in self.parents.items():
    #         for label in labels:
    #             weight = graph.label_weights[label]
    #             parent_embedding, vectors, k_hop = parent.coalesce_dependencies(graph, vectors, k_hop-1, method)
    #             weighted_embedding = weight * parent_embedding
    #             vectors.append(weighted_embedding)

        
    #     if vectors:
    #         stacked = torch.stack(vectors, dim=0)
    #         aggregated = method(stacked, dim=0)
    #         combined_embedding = self.embedding + aggregated
    #     else:
    #         combined_embedding = self.embedding
        
    #     return combined_embedding, vectors, k_hop

    def collect_neighbours(self, k):
        # need correct logic... 
        #add: pass k-1-hop tree to next with self.id
         # maybe just save as {hop_num(corresponding to gcn layer) : embedding, edge label}
        
        local_tree = []
        for parent, labels in self.parents.items():
            for label in labels:
                
                local_tree.append({self.id:(parent.embedding, label, self.id)})
        return parent, local_tree
                    
                    
        # return tree

    #     for parent, labels in self.parents.items():
    #         for label in labels:
    #             parent.message(self.id, label)

    # def message(self, target_id, label):
        
        
    
    def print_out_degree(self):
        out_edges = [(label,target.id) for label,target in self.out_edges]
        print(f"Out edges: {out_edges}") if out_edges else print(f'Node {self.id} has no children')

    def adjust_embeddings(self, new_embedding):
        self.embedding = new_embedding

    def add_parent(self, parent_node, label):
        if parent_node not in self.parents:
            self.parents[parent_node] = []
        self.parents[parent_node].append(label)

    def add_child(self, child_node, label):
        if child_node not in self.children:
            self.children[child_node] = []
        self.children[child_node].append(label)
        self.add_out_edge(label, child_node)

    def add_out_edge(self, label, target):
        self.out_edges.append((label, target))

    def step(self):
        if not self.children:
            return None
        edge_label, target_node = random.choice(self.out_edges)
        return (target_node, edge_label)

class Graph:
    def __init__(self):
        self.nodes = {}
        self.label_weights = {}
        self.unique_labels = set()

    def add_node(self, id_):
        if id_ not in self.nodes:
            self.nodes[id_] = Node(id_)

    def add_edge(self, from_id, to_id, label):
        if label not in self.unique_labels:
            self.unique_labels.add(label)
        if from_id not in self.nodes:
            self.add_node(from_id)
        if to_id not in self.nodes:
            self.add_node(to_id)
        
        from_node = self.nodes[from_id]
        to_node = self.nodes[to_id]
        from_node.add_child(to_node, label)
        to_node.add_parent(from_node, label)

    def initialize_label_weights(self):
        for label in list(self.unique_labels):
            self.label_weights[label] = torch.rand(DIM_W,dtype=torch.float16, requires_grad=True)
    
    def get_parents(self, id_):
        node = self.nodes.get(id_)
        return {parent.id: labels for parent, labels in node.parents.items()}

    def get_children(self, id_):
        node = self.nodes.get(id_)
        return {child.id: labels for child, labels in node.children.items()}


## Test some stuff:

In [487]:
graph=Graph()
nodes=[]
num_nodes = 5
for n in range(97,97+num_nodes):
    graph.add_node(chr(n))
    nodes.append(chr(n))

preds = ["geometry:triangle","rdfs:subClassOf","FOAF:likes","rdfs:subClassOf","rdfs:domain","FOAF:knows","rdfs:isDefinedBy"]
for e in range(100):
    obj = random.choice(nodes)
    subj = random.choice([node for node in nodes if node != obj])
    pred = random.choice(preds)
    graph.add_edge(obj,subj,pred)
graph.initialize_label_weights()

In [488]:
A = graph.nodes["a"]
node=A
k_hops = 3
dep_tree = {}
def recursive_k_hop(node,dep_tree,dep_tree_entry,k_hop, max_hop):
    i = 0
    while dep_tree_entry:
        parent, dep_tree_entry = node.collect_neighbours(k_hop)
        dep_tree = recursive_k_hop(parent, dep_tree, dep_tree_entry ,k_hop+1,max_hop)
        i += 1
    # for parent, dep_tree_entry in node.collect_neighbours(k_hop):
    #     dep_tree[k_hop][i] = dep_tree_entry
    #     dep_tree = recursive_k_hop(parent, dep_tree, k_hop+1,max_hop)
    #     i += 1
    if k_hop >= max_hop:
        print(f"k{k_hop}, node {node.id} done")
        return dep_tree 


dep_tree_entry = node.collect_neighbours(1)
dep_tree[1] = {node.id:dep_tree_entry}

dep_tree = recursive_k_hop(node,dep_tree,dep_tree_entry,1,3)
print(dep_tree)

RecursionError: maximum recursion depth exceeded

In [473]:
A = graph.nodes["b"]
node=A
node.collect_neighbours(3)

(<__main__.Node at 0x7dfff7123f50>,
 [{'b': (tensor([0.9092, 0.0986, 0.7871, 0.9810, 0.4604], dtype=torch.float16,
           requires_grad=True),
    'rdfs:isDefinedBy',
    'b')},
  {'b': (tensor([0.9092, 0.0986, 0.7871, 0.9810, 0.4604], dtype=torch.float16,
           requires_grad=True),
    'rdfs:domain',
    'b')},
  {'b': (tensor([0.9092, 0.0986, 0.7871, 0.9810, 0.4604], dtype=torch.float16,
           requires_grad=True),
    'rdfs:isDefinedBy',
    'b')},
  {'b': (tensor([0.9092, 0.0986, 0.7871, 0.9810, 0.4604], dtype=torch.float16,
           requires_grad=True),
    'geometry:triangle',
    'b')},
  {'b': (tensor([0.5767, 0.3511, 0.3530, 0.2979, 0.9175], dtype=torch.float16,
           requires_grad=True),
    'geometry:triangle',
    'b')},
  {'b': (tensor([0.5767, 0.3511, 0.3530, 0.2979, 0.9175], dtype=torch.float16,
           requires_grad=True),
    'FOAF:likes',
    'b')},
  {'b': (tensor([0.8623, 0.2974, 0.5112, 0.2007, 0.3359], dtype=torch.float16,
           require

In [385]:
coalesced = node.coalesce_dependencies(graph)

AttributeError: 'Node' object has no attribute 'coalesce_dependencies'

In [377]:
coalesced[0]

tensor([13.4453,  8.7500, 11.0000, 14.2422, 14.6641], dtype=torch.float16,
       grad_fn=<AddBackward0>)

In [375]:
node.print_out_degree()

Out edges: [('FOAF:knows', 'b'), ('rdfs:isDefinedBy', 'b'), ('rdfs:subClassOf', 'c'), ('rdfs:isDefinedBy', 'd'), ('rdfs:subClassOf', 'd'), ('rdfs:subClassOf', 'b'), ('FOAF:knows', 'c'), ('rdfs:isDefinedBy', 'c'), ('FOAF:likes', 'e'), ('rdfs:domain', 'e'), ('rdfs:subClassOf', 'e'), ('rdfs:subClassOf', 'e'), ('rdfs:subClassOf', 'c'), ('geometry:triangle', 'b'), ('rdfs:domain', 'e'), ('rdfs:isDefinedBy', 'c'), ('geometry:triangle', 'c'), ('rdfs:domain', 'e'), ('FOAF:likes', 'd'), ('rdfs:subClassOf', 'c')]


In [347]:
coalesced [1]

[tensor([0.0311, 0.0190, 0.0280, 0.7148, 0.1625], dtype=torch.float16,
        grad_fn=<MulBackward0>),
 tensor([0.0582, 0.2112, 0.2373, 0.2507, 0.2003], dtype=torch.float16,
        grad_fn=<MulBackward0>),
 tensor([0.0117, 0.0257, 0.4363, 0.4351, 0.1278], dtype=torch.float16,
        grad_fn=<MulBackward0>),
 tensor([0.0311, 0.0190, 0.0280, 0.7148, 0.1625], dtype=torch.float16,
        grad_fn=<MulBackward0>),
 tensor([0.0117, 0.0257, 0.4363, 0.4351, 0.1278], dtype=torch.float16,
        grad_fn=<MulBackward0>),
 tensor([0.2400, 0.0247, 0.0255, 0.5996, 0.0487], dtype=torch.float16,
        grad_fn=<MulBackward0>),
 tensor([0.1338, 0.0077, 0.0684, 0.4321, 0.0723], dtype=torch.float16,
        grad_fn=<MulBackward0>),
 tensor([0.0540, 0.0521, 0.0484, 0.4434, 0.0305], dtype=torch.float16,
        grad_fn=<MulBackward0>),
 tensor([0.0897, 0.4609, 0.0110, 0.8672, 0.4043], dtype=torch.float16,
        grad_fn=<MulBackward0>),
 tensor([0.0604, 0.3433, 0.1132, 0.5894, 0.1580], dtype=torch.fl

In [195]:
node,edge_label = node.step()
# node = graph.nodes[node_id]
node.id

'c'

In [201]:
walk = True
lambda_ = 0.01
while walk:
    node,edge_label = node.step()
    # node = graph.nodes[node_id]
    walk = random.random()>lambda_
    print(node.print_out_degree())


Out edges: [('FOAF:likes', 'b'), ('FOAF:knows', 'a'), ('FOAF:knows', 'a'), ('rdfs:subClassOf', 'a'), ('rdfs:domain', 'b'), ('FOAF:likes', 'a'), ('FOAF:knows', 'a'), ('FOAF:knows', 'a'), ('rdfs:isDefinedBy', 'b'), ('geometry:triangle', 'a'), ('rdfs:subClassOf', 'a'), ('FOAF:likes', 'a'), ('rdfs:subClassOf', 'a'), ('rdfs:subClassOf', 'a'), ('FOAF:knows', 'a'), ('rdfs:subClassOf', 'a'), ('geometry:triangle', 'a'), ('geometry:triangle', 'a'), ('rdfs:subClassOf', 'a'), ('rdfs:domain', 'b'), ('rdfs:isDefinedBy', 'a'), ('rdfs:subClassOf', 'b'), ('FOAF:knows', 'a'), ('rdfs:isDefinedBy', 'a'), ('FOAF:knows', 'a')]
None
Out edges: [('FOAF:likes', 'c'), ('FOAF:knows', 'b'), ('FOAF:knows', 'b'), ('FOAF:likes', 'b'), ('rdfs:subClassOf', 'c'), ('FOAF:knows', 'b'), ('rdfs:subClassOf', 'b'), ('rdfs:isDefinedBy', 'b'), ('rdfs:subClassOf', 'c'), ('rdfs:isDefinedBy', 'b'), ('rdfs:subClassOf', 'b'), ('rdfs:domain', 'c'), ('FOAF:knows', 'c'), ('rdfs:subClassOf', 'c'), ('rdfs:isDefinedBy', 'c'), ('rdfs:isDe

### cashew: try graphgym package :)
# Proposed GNN architecture:
## Transformation block >>>
### * linear
### * batch norm * <  my intuition is that this could replace mean() operation, just use vectorized sum() to reduce computational complexity.
### * dropout * < On linear layer in the message function
### * activation * < parametric relu = max(x,0) + alpha * min(x,0) ... alpha is trainable.
### * attention * < I'm not sure if relational weights as in RGCN fall into this category. If they are complementary in any way.
## <<< End transformation block
### * aggregation by some problem dependant function i.e. mean(), min/max/avg..._pooling(), lstm(cat(edge_embeddings)) ...
#### aggregation note: inverted degree matrix * adjacency matrix = avg(adjacency matrix)

# classical GCN:

## important design choice here... use batch norm after each layer? Normalize explicitly?
## messages = layer weight * normalized messages from prev layers
## aggregation = sum(messages) --> relu

### todo: add weighted average method. I.e. learnable row vector of size feature dim (must vectorize torch.mean explicitly for this)

In [3]:
# def aggregate(features): #this creates an aggregation directly as a matrix op
#     agg = torch.stack(features)
#     return agg, torch.mean(agg, dim=0)

# def coalesce(features):

# def normalize(messages):
#     num = len(messages)
    

# def relu(features):
#     return relu(features)

# GraphSAGE
## aggregate incoming messages (can be mean(messages, dim=0), can be a max pooling on mlp(message), can be LSTM(shuffle(messages) as mini-batch), can be sum without average (maybe this leads to batch norm later?)
## concat current node message --> relu --> send

## Uses L2 Norm as root squared error of embeddings at every layer.

# GAT

# Architectural notes:

## GCN, but vector weighting matrix is learned (which nodes to attend to and ./ unsure./ which parts of the embedding vectors/features to attend to \.\.

### how can we handle permutation invariance?

### seems that attention weights are graph conditional on search algorithm dependant

### ^ wrong. It's a function of (and on) embeddings of different node embeddings at the previous step.

### softmax ()

### parameter matrix a can be a parameter matrix on a learned single layer mlp that processes the concatenated input vectors.

### parameter matrix a is learned together with weight matrix w.

### multi-head attention, multiple relu(a) matrices.

### each a is initialized randomly, then aggregated to produce a single output

### can be parallellized worker per message.

### sparse matrix... fixed number of parameters.

# Implications/discussion

### asymmetric importance weighting

### weights are still independant of graph size, even though more complex analysis of the graph can be performed.

### graph attention mechanism scales linearly in graph size due to locality

### cool visualization of attention mechanism (implicit clustering) cora citation paper

### improved performance over GCN in some cases.




# Test stuff and transform into main() below...

In [4]:
coalesce((edge_1,edge_2, edge_3))

NameError: name 'coalesce' is not defined

In [5]:
dfs = GraphSearch(graph, protocol='BFS')

walk = True
lambda_ = 0.1
node_id = 1
stack = deque([node_id])
print(stack)
while walk:
    node_id, stack = dfs.step(stack)
    if random.random() < lambda_:
        walk = False
print(graph)

deque([1])
1


NameError: name 'coalesce' is not defined